config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :books,          only: [:create, :destroy]
  resources :readings,          only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %><% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_reading_form.html.erb
<!-- à revoir -->
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <input type="text" id="book-title" class="form-control">
      <div id="results">
      </div>
    </div>
  </div>

<!-- Lors du click sur un résultat de recherche, ce formulaire (caché) est remplis puis il est soumis
     vers l'action create de la ressource offer. -->
<%= form_for(@book, url: reading_path) do |f| %>
  <%= f.text_field :title, class: "hidden" %>
  <%= f.text_field :subtitle, class: "hidden" %>
  <%= f.text_field :description, class: "hidden" %>
  <%= f.text_field :author, class: "hidden" %>
  <%= f.text_field :category, class: 'hidden' %>
<% end %>


<div class= "text-center col-xs-6 col-md-offset-3" >
  <%= simple_form_for @book, :url => book_offer_path do |f| %>
    <%= f.input :select_category, collection: %w(business ux), selected: "développement", label: "Choose a category" %>
  <% end %>
</div>

<%= form_for(@reading) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="field">
    <%= f.text_area :grade, placeholder: "Grade this book" %>
  </div>

  <div class="field">
    <%= f.text_area :comment, placeholder: "Did you like this book?" %>
  </div>

  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>



<%= content_for :after_js do %>
  <%= javascript_tag do %>
    global_google_api_key = "<%= ENV["GOOGLE_API_KEY"] %>";
    $( function(){ $('#book-title').on('keyup', search_book);} );
  <% end %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.readings.count, "reading") %></span>

app/views/shared/app:views:shared:_feed.html.erb
<% if @feed_items.any? %>
  <ol class="readings">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>